name: Update EPG

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests beautifulsoup4 lxml

    - name: Update EPG
      run: python update_epg.py 2>&1 | tee update_epg.log

    - name: Store PAT
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global credential.helper store -file ~/.git-credentials <<EOF
        https://
        protocol=https
        host=github.com
        username=github-jl14
        password=${PAT}
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-jl14'
        git config --global user.email 'alt444.001@gmail.com'
        git add epg.xml update_epg.log
        git commit -m 'Update EPG'
        git push https://github.com/

    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: update_epg_log
        path: update_epg.log
